name: GH Actions Test

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches: [main]

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: MetRonnie/release-actions/create-release@gh-cli
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # commitish: f38719a32c08bb650978fd2a09b05bdc22550670
          tag_name: '1.2.55'
          release_name: the-cage
          prerelease: false
          body: |
            Blah blah

            Cylc 8 can be installed via pypi or Conda - you don't need to download this release directly.
            See the [installation](https://cylc.github.io/cylc-doc/latest/html/installation.html) section of the documentation.

      - run: echo ${{ steps.create-release.outputs.html_url }}
