name: GH Actions Test

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches: [main]

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cylc/release-actions/configure-git@v1

      - run: |
          git checkout -b hmm
          echo "Testing" >> README.md
          git commit -a -m 'Testing'
          git push

      - uses: MetRonnie/release-actions/create-pr@set-output
        with:
          head: hmm
          base: oblong24
          title: Testing
          body: 🧪
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
