name: GH Actions Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - id: one
        run: echo "::set-output name=thing::true"

      - id: two
        run: echo "::notice::Hello there"

      - if: steps.one.outputs.thing
        run: echo "ONE!"

      - if: steps.two.outputs.thing
        run: echo "TWO!"
